# Generated by Django 5.1.5 on 2025-04-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkbinary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ali',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ali',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='git',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='git',
            name='username',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='google',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='googlep',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ram',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ram',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
